spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: recipe_dev_user
    password: dev
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/mysql-schema.sql
