spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: recipe_dev_user
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
