spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_prod
    username: recipe_prod_user
    password: prod
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: false
